import { type Workflow, WorkflowSchema, validate } from '@mobile-automation/workflow-schema';
import { NativeModules } from 'react-native';

/**
 * Workflow persistence, over the native Room module (ADR 0005).
 *
 * The document crosses as a JSON string, and this is where it is **validated on the way in**.
 * A document written by an older version of the app, or hand-edited, or generated by a model,
 * could be anything - and loading it unchecked would put an invalid workflow onto the canvas
 * where every subsequent operation assumes it is well-formed.
 *
 * The store holds the working copy; this holds the durable one. Keeping them distinct is what
 * makes "unsaved changes" a real state rather than a guess (ADR 0003).
 */

type WorkflowStorageNative = {
  list: () => Promise<
    {
      id: string;
      name: string;
      description: string | null;
      nodeCount: number;
      updatedAtEpochMs: number;
    }[]
  >;
  load: (id: string) => Promise<string | null>;
  save: (id: string, document: string) => Promise<void>;
  remove: (id: string) => Promise<void>;
  count: () => Promise<number>;
};

const native = (NativeModules as { WorkflowStorage?: WorkflowStorageNative }).WorkflowStorage;

export const isStorageAvailable = (): boolean => native !== undefined;

export type WorkflowSummary = {
  readonly id: string;
  readonly name: string;
  readonly description: string | null;
  readonly nodeCount: number;
  readonly updatedAtEpochMs: number;
};

/** The saved workflows, newest first. Never reads a document. */
export const listWorkflows = async (): Promise<readonly WorkflowSummary[]> => {
  if (native === undefined) return [];
  return native.list();
};

export type LoadResult =
  | { readonly ok: true; readonly workflow: Workflow }
  | { readonly ok: false; readonly reason: 'not-found' | 'invalid'; readonly detail?: string };

/**
 * Loads and validates a workflow.
 *
 * "Not found" and "invalid" are kept apart because they are different situations for the user:
 * one means the workflow is gone, the other that it exists but cannot be opened - and only the
 * second is worth reporting as a fault.
 */
export const loadWorkflow = async (id: string): Promise<LoadResult> => {
  if (native === undefined) return { ok: false, reason: 'not-found' };

  const document = await native.load(id);
  if (document === null) return { ok: false, reason: 'not-found' };

  let parsed: unknown;
  try {
    parsed = JSON.parse(document);
  } catch {
    return { ok: false, reason: 'invalid', detail: 'The saved workflow is not readable.' };
  }

  const result = validate(WorkflowSchema, parsed);

  if (!result.ok) {
    return {
      ok: false,
      reason: 'invalid',
      detail: result.issues.map((issue) => issue.message).join('; '),
    };
  }

  return { ok: true, workflow: result.value };
};

/**
 * Saves a workflow, validating first.
 *
 * Refusing to save an invalid document is deliberate: a workflow that cannot be loaded back is
 * not saved in any useful sense, and discovering that on next open is far worse than being
 * told now.
 */
export const saveWorkflow = async (
  workflow: Workflow,
): Promise<{ readonly ok: true } | { readonly ok: false; readonly issues: readonly string[] }> => {
  const result = validate(WorkflowSchema, workflow);

  if (!result.ok) {
    return {
      ok: false,
      issues: result.issues.map((issue) =>
        issue.path === '' ? issue.message : `${issue.path}: ${issue.message}`,
      ),
    };
  }

  if (native === undefined) {
    return { ok: false, issues: ['Storage is not available in this build.'] };
  }

  await native.save(workflow.id, JSON.stringify(workflow));
  return { ok: true };
};

export const deleteWorkflow = async (id: string): Promise<void> => {
  await native?.remove(id);
};

export const countWorkflows = async (): Promise<number> => native?.count() ?? 0;
